00
 

                       09Installer Boot Options07

 -  To disable hardware probing, type: 0flinux noprobe <ENTER>07.  

 -  To enable rescue mode, type: 0flinux rescue <ENTER>07.  
    Press 0f<F5>07 for more information about rescue mode.

 -  To enable the NFS installation method, type: 0flinux
    method=nfs://server/share/path <ENTER>07, where 0fserver07 is the
    hostname or IP address of the NFS server and
    0f/share/path07 is the path to the repository on the NFS server.

 -  To test the memory in your system, type: 0fmemtest86 <ENTER>07.
    (This option is only available when booting from CD.)

02[F1-Main] [F2-Options] [F3-General] [F4-Kernel] [F5-Rescue]07

